// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.platform.dto;

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code example.Direction}
   */
  public enum Direction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LEFT = 0;</code>
     */
    LEFT(0),
    /**
     * <code>RIGHT = 1;</code>
     */
    RIGHT(1),
    /**
     * <code>UP = 2;</code>
     */
    UP(2),
    /**
     * <code>DOWN = 3;</code>
     */
    DOWN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LEFT = 0;</code>
     */
    public static final int LEFT_VALUE = 0;
    /**
     * <code>RIGHT = 1;</code>
     */
    public static final int RIGHT_VALUE = 1;
    /**
     * <code>UP = 2;</code>
     */
    public static final int UP_VALUE = 2;
    /**
     * <code>DOWN = 3;</code>
     */
    public static final int DOWN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Direction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Direction forNumber(int value) {
      switch (value) {
        case 0: return LEFT;
        case 1: return RIGHT;
        case 2: return UP;
        case 3: return DOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Direction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Direction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
            public Direction findValueByNumber(int number) {
              return Direction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Person.getDescriptor().getEnumTypes().get(0);
    }

    private static final Direction[] VALUES = values();

    public static Direction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Direction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:example.Direction)
  }

  public interface studentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double weight = 3;</code>
     * @return The weight.
     */
    double getWeight();

    /**
     * <code>int64 seq = 4;</code>
     * @return The seq.
     */
    long getSeq();

    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    String getAddress();
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The enum numeric value on the wire for direct.
     */
    int getDirectValue();
    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The direct.
     */
    Person.Direction getDirect();

    /**
     * <code>bool flag = 7;</code>
     * @return The flag.
     */
    boolean getFlag();

    /**
     * <code>bytes imgs = 8;</code>
     * @return The imgs.
     */
    com.google.protobuf.ByteString getImgs();
  }
  /**
   * Protobuf type {@code example.student}
   */
  public static final class student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.student)
      studentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use student.newBuilder() to construct.
    private student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private student() {
      name_ = "";
      address_ = "";
      direct_ = 0;
      imgs_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new student();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 25: {

              weight_ = input.readDouble();
              break;
            }
            case 32: {

              seq_ = input.readInt64();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              direct_ = rawValue;
              break;
            }
            case 56: {

              flag_ = input.readBool();
              break;
            }
            case 66: {

              imgs_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_example_student_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_example_student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.student.class, Person.student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private double weight_;
    /**
     * <code>double weight = 3;</code>
     * @return The weight.
     */
    @Override
    public double getWeight() {
      return weight_;
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private long seq_;
    /**
     * <code>int64 seq = 4;</code>
     * @return The seq.
     */
    @Override
    public long getSeq() {
      return seq_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile Object address_;
    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    @Override
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    @Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECT_FIELD_NUMBER = 6;
    private int direct_;
    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The enum numeric value on the wire for direct.
     */
    @Override public int getDirectValue() {
      return direct_;
    }
    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The direct.
     */
    @Override public Person.Direction getDirect() {
      @SuppressWarnings("deprecation")
      Person.Direction result = Person.Direction.valueOf(direct_);
      return result == null ? Person.Direction.UNRECOGNIZED : result;
    }

    public static final int FLAG_FIELD_NUMBER = 7;
    private boolean flag_;
    /**
     * <code>bool flag = 7;</code>
     * @return The flag.
     */
    @Override
    public boolean getFlag() {
      return flag_;
    }

    public static final int IMGS_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString imgs_;
    /**
     * <code>bytes imgs = 8;</code>
     * @return The imgs.
     */
    @Override
    public com.google.protobuf.ByteString getImgs() {
      return imgs_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (weight_ != 0D) {
        output.writeDouble(3, weight_);
      }
      if (seq_ != 0L) {
        output.writeInt64(4, seq_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (direct_ != Person.Direction.LEFT.getNumber()) {
        output.writeEnum(6, direct_);
      }
      if (flag_ != false) {
        output.writeBool(7, flag_);
      }
      if (!imgs_.isEmpty()) {
        output.writeBytes(8, imgs_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, weight_);
      }
      if (seq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, seq_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (direct_ != Person.Direction.LEFT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, direct_);
      }
      if (flag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, flag_);
      }
      if (!imgs_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, imgs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person.student)) {
        return super.equals(obj);
      }
      Person.student other = (Person.student) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (Double.doubleToLongBits(getWeight())
          != Double.doubleToLongBits(
              other.getWeight())) return false;
      if (getSeq()
          != other.getSeq()) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (direct_ != other.direct_) return false;
      if (getFlag()
          != other.getFlag()) return false;
      if (!getImgs()
          .equals(other.getImgs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getWeight()));
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeq());
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + DIRECT_FIELD_NUMBER;
      hash = (53 * hash) + direct_;
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFlag());
      hash = (37 * hash) + IMGS_FIELD_NUMBER;
      hash = (53 * hash) + getImgs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person.student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Person.student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person.student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.student)
        Person.studentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_example_student_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_example_student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.student.class, Person.student.Builder.class);
      }

      // Construct using Person.student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        weight_ = 0D;

        seq_ = 0L;

        address_ = "";

        direct_ = 0;

        flag_ = false;

        imgs_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_example_student_descriptor;
      }

      @Override
      public Person.student getDefaultInstanceForType() {
        return Person.student.getDefaultInstance();
      }

      @Override
      public Person.student build() {
        Person.student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Person.student buildPartial() {
        Person.student result = new Person.student(this);
        result.id_ = id_;
        result.name_ = name_;
        result.weight_ = weight_;
        result.seq_ = seq_;
        result.address_ = address_;
        result.direct_ = direct_;
        result.flag_ = flag_;
        result.imgs_ = imgs_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.student) {
          return mergeFrom((Person.student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.student other) {
        if (other == Person.student.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        if (other.getSeq() != 0L) {
          setSeq(other.getSeq());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.direct_ != 0) {
          setDirectValue(other.getDirectValue());
        }
        if (other.getFlag() != false) {
          setFlag(other.getFlag());
        }
        if (other.getImgs() != com.google.protobuf.ByteString.EMPTY) {
          setImgs(other.getImgs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>double weight = 3;</code>
       * @return The weight.
       */
      @Override
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>double weight = 3;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(double value) {

        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {

        weight_ = 0D;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <code>int64 seq = 4;</code>
       * @return The seq.
       */
      @Override
      public long getSeq() {
        return seq_;
      }
      /**
       * <code>int64 seq = 4;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(long value) {

        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 seq = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {

        seq_ = 0L;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>string address = 5;</code>
       * @return The address.
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        address_ = value;
        onChanged();
        return this;
      }

      private int direct_ = 0;
      /**
       * <code>.example.Direction direct = 6;</code>
       * @return The enum numeric value on the wire for direct.
       */
      @Override public int getDirectValue() {
        return direct_;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @param value The enum numeric value on the wire for direct to set.
       * @return This builder for chaining.
       */
      public Builder setDirectValue(int value) {

        direct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @return The direct.
       */
      @Override
      public Person.Direction getDirect() {
        @SuppressWarnings("deprecation")
        Person.Direction result = Person.Direction.valueOf(direct_);
        return result == null ? Person.Direction.UNRECOGNIZED : result;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @param value The direct to set.
       * @return This builder for chaining.
       */
      public Builder setDirect(Person.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }

        direct_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirect() {

        direct_ = 0;
        onChanged();
        return this;
      }

      private boolean flag_ ;
      /**
       * <code>bool flag = 7;</code>
       * @return The flag.
       */
      @Override
      public boolean getFlag() {
        return flag_;
      }
      /**
       * <code>bool flag = 7;</code>
       * @param value The flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlag(boolean value) {

        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool flag = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlag() {

        flag_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString imgs_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes imgs = 8;</code>
       * @return The imgs.
       */
      @Override
      public com.google.protobuf.ByteString getImgs() {
        return imgs_;
      }
      /**
       * <code>bytes imgs = 8;</code>
       * @param value The imgs to set.
       * @return This builder for chaining.
       */
      public Builder setImgs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        imgs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes imgs = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearImgs() {

        imgs_ = getDefaultInstance().getImgs();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.student)
    }

    // @@protoc_insertion_point(class_scope:example.student)
    private static final Person.student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person.student();
    }

    public static Person.student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<student>
        PARSER = new com.google.protobuf.AbstractParser<student>() {
      @Override
      public student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<student> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<student> getParserForType() {
      return PARSER;
    }

    @Override
    public Person.student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface personOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.example.student student = 3;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <code>.example.student student = 3;</code>
     * @return The student.
     */
    Person.student getStudent();
    /**
     * <code>.example.student student = 3;</code>
     */
    Person.studentOrBuilder getStudentOrBuilder();

    /**
     * <code>bytes address = 4;</code>
     * @return The address.
     */
    com.google.protobuf.ByteString getAddress();
  }
  /**
   * Protobuf type {@code example.person}
   */
  public static final class person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.person)
      personOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use person.newBuilder() to construct.
    private person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private person() {
      name_ = "";
      address_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new person();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              Person.student.Builder subBuilder = null;
              if (student_ != null) {
                subBuilder = student_.toBuilder();
              }
              student_ = input.readMessage(Person.student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(student_);
                student_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {

              address_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_example_person_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_example_person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.person.class, Person.person.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STUDENT_FIELD_NUMBER = 3;
    private Person.student student_;
    /**
     * <code>.example.student student = 3;</code>
     * @return Whether the student field is set.
     */
    @Override
    public boolean hasStudent() {
      return student_ != null;
    }
    /**
     * <code>.example.student student = 3;</code>
     * @return The student.
     */
    @Override
    public Person.student getStudent() {
      return student_ == null ? Person.student.getDefaultInstance() : student_;
    }
    /**
     * <code>.example.student student = 3;</code>
     */
    @Override
    public Person.studentOrBuilder getStudentOrBuilder() {
      return getStudent();
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 4;</code>
     * @return The address.
     */
    @Override
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (student_ != null) {
        output.writeMessage(3, getStudent());
      }
      if (!address_.isEmpty()) {
        output.writeBytes(4, address_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (student_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStudent());
      }
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person.person)) {
        return super.equals(obj);
      }
      Person.person other = (Person.person) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasStudent() != other.hasStudent()) return false;
      if (hasStudent()) {
        if (!getStudent()
            .equals(other.getStudent())) return false;
      }
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasStudent()) {
        hash = (37 * hash) + STUDENT_FIELD_NUMBER;
        hash = (53 * hash) + getStudent().hashCode();
      }
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person.person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Person.person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person.person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.person)
        Person.personOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_example_person_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_example_person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.person.class, Person.person.Builder.class);
      }

      // Construct using Person.person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (studentBuilder_ == null) {
          student_ = null;
        } else {
          student_ = null;
          studentBuilder_ = null;
        }
        address_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_example_person_descriptor;
      }

      @Override
      public Person.person getDefaultInstanceForType() {
        return Person.person.getDefaultInstance();
      }

      @Override
      public Person.person build() {
        Person.person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Person.person buildPartial() {
        Person.person result = new Person.person(this);
        result.id_ = id_;
        result.name_ = name_;
        if (studentBuilder_ == null) {
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.person) {
          return mergeFrom((Person.person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.person other) {
        if (other == Person.person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasStudent()) {
          mergeStudent(other.getStudent());
        }
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private Person.student student_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Person.student, Person.student.Builder, Person.studentOrBuilder> studentBuilder_;
      /**
       * <code>.example.student student = 3;</code>
       * @return Whether the student field is set.
       */
      public boolean hasStudent() {
        return studentBuilder_ != null || student_ != null;
      }
      /**
       * <code>.example.student student = 3;</code>
       * @return The student.
       */
      public Person.student getStudent() {
        if (studentBuilder_ == null) {
          return student_ == null ? Person.student.getDefaultInstance() : student_;
        } else {
          return studentBuilder_.getMessage();
        }
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      public Builder setStudent(Person.student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          student_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      public Builder setStudent(
          Person.student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          student_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      public Builder mergeStudent(Person.student value) {
        if (studentBuilder_ == null) {
          if (student_ != null) {
            student_ =
              Person.student.newBuilder(student_).mergeFrom(value).buildPartial();
          } else {
            student_ = value;
          }
          onChanged();
        } else {
          studentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = null;
          onChanged();
        } else {
          student_ = null;
          studentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      public Person.student.Builder getStudentBuilder() {

        onChanged();
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      public Person.studentOrBuilder getStudentOrBuilder() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          return student_ == null ?
              Person.student.getDefaultInstance() : student_;
        }
      }
      /**
       * <code>.example.student student = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Person.student, Person.student.Builder, Person.studentOrBuilder>
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Person.student, Person.student.Builder, Person.studentOrBuilder>(
                  getStudent(),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 4;</code>
       * @return The address.
       */
      @Override
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 4;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.person)
    }

    // @@protoc_insertion_point(class_scope:example.person)
    private static final Person.person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person.person();
    }

    public static Person.person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<person>
        PARSER = new com.google.protobuf.AbstractParser<person>() {
      @Override
      public person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<person> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<person> getParserForType() {
      return PARSER;
    }

    @Override
    public Person.person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface all_personOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.all_person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    java.util.List<Person.person>
        getPerList();
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    Person.person getPer(int index);
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    int getPerCount();
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    java.util.List<? extends Person.personOrBuilder>
        getPerOrBuilderList();
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    Person.personOrBuilder getPerOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code example.all_person}
   */
  public static final class all_person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.all_person)
      all_personOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use all_person.newBuilder() to construct.
    private all_person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private all_person() {
      per_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new all_person();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private all_person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                per_ = new java.util.ArrayList<Person.person>();
                mutable_bitField0_ |= 0x00000001;
              }
              per_.add(
                  input.readMessage(Person.person.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          per_ = java.util.Collections.unmodifiableList(per_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_example_all_person_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_example_all_person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.all_person.class, Person.all_person.Builder.class);
    }

    public static final int PER_FIELD_NUMBER = 1;
    private java.util.List<Person.person> per_;
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    @Override
    public java.util.List<Person.person> getPerList() {
      return per_;
    }
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    @Override
    public java.util.List<? extends Person.personOrBuilder>
        getPerOrBuilderList() {
      return per_;
    }
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    @Override
    public int getPerCount() {
      return per_.size();
    }
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    @Override
    public Person.person getPer(int index) {
      return per_.get(index);
    }
    /**
     * <code>repeated .example.person Per = 1;</code>
     */
    @Override
    public Person.personOrBuilder getPerOrBuilder(
        int index) {
      return per_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < per_.size(); i++) {
        output.writeMessage(1, per_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < per_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, per_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person.all_person)) {
        return super.equals(obj);
      }
      Person.all_person other = (Person.all_person) obj;

      if (!getPerList()
          .equals(other.getPerList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPerCount() > 0) {
        hash = (37 * hash) + PER_FIELD_NUMBER;
        hash = (53 * hash) + getPerList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person.all_person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.all_person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.all_person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.all_person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.all_person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.all_person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.all_person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.all_person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.all_person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Person.all_person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.all_person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.all_person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person.all_person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.all_person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.all_person)
        Person.all_personOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_example_all_person_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_example_all_person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.all_person.class, Person.all_person.Builder.class);
      }

      // Construct using Person.all_person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPerFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (perBuilder_ == null) {
          per_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          perBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_example_all_person_descriptor;
      }

      @Override
      public Person.all_person getDefaultInstanceForType() {
        return Person.all_person.getDefaultInstance();
      }

      @Override
      public Person.all_person build() {
        Person.all_person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Person.all_person buildPartial() {
        Person.all_person result = new Person.all_person(this);
        int from_bitField0_ = bitField0_;
        if (perBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            per_ = java.util.Collections.unmodifiableList(per_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.per_ = per_;
        } else {
          result.per_ = perBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.all_person) {
          return mergeFrom((Person.all_person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.all_person other) {
        if (other == Person.all_person.getDefaultInstance()) return this;
        if (perBuilder_ == null) {
          if (!other.per_.isEmpty()) {
            if (per_.isEmpty()) {
              per_ = other.per_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePerIsMutable();
              per_.addAll(other.per_);
            }
            onChanged();
          }
        } else {
          if (!other.per_.isEmpty()) {
            if (perBuilder_.isEmpty()) {
              perBuilder_.dispose();
              perBuilder_ = null;
              per_ = other.per_;
              bitField0_ = (bitField0_ & ~0x00000001);
              perBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPerFieldBuilder() : null;
            } else {
              perBuilder_.addAllMessages(other.per_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.all_person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.all_person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Person.person> per_ =
        java.util.Collections.emptyList();
      private void ensurePerIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          per_ = new java.util.ArrayList<Person.person>(per_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Person.person, Person.person.Builder, Person.personOrBuilder> perBuilder_;

      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public java.util.List<Person.person> getPerList() {
        if (perBuilder_ == null) {
          return java.util.Collections.unmodifiableList(per_);
        } else {
          return perBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public int getPerCount() {
        if (perBuilder_ == null) {
          return per_.size();
        } else {
          return perBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Person.person getPer(int index) {
        if (perBuilder_ == null) {
          return per_.get(index);
        } else {
          return perBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder setPer(
          int index, Person.person value) {
        if (perBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePerIsMutable();
          per_.set(index, value);
          onChanged();
        } else {
          perBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder setPer(
          int index, Person.person.Builder builderForValue) {
        if (perBuilder_ == null) {
          ensurePerIsMutable();
          per_.set(index, builderForValue.build());
          onChanged();
        } else {
          perBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder addPer(Person.person value) {
        if (perBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePerIsMutable();
          per_.add(value);
          onChanged();
        } else {
          perBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder addPer(
          int index, Person.person value) {
        if (perBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePerIsMutable();
          per_.add(index, value);
          onChanged();
        } else {
          perBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder addPer(
          Person.person.Builder builderForValue) {
        if (perBuilder_ == null) {
          ensurePerIsMutable();
          per_.add(builderForValue.build());
          onChanged();
        } else {
          perBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder addPer(
          int index, Person.person.Builder builderForValue) {
        if (perBuilder_ == null) {
          ensurePerIsMutable();
          per_.add(index, builderForValue.build());
          onChanged();
        } else {
          perBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder addAllPer(
          Iterable<? extends Person.person> values) {
        if (perBuilder_ == null) {
          ensurePerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, per_);
          onChanged();
        } else {
          perBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder clearPer() {
        if (perBuilder_ == null) {
          per_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          perBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Builder removePer(int index) {
        if (perBuilder_ == null) {
          ensurePerIsMutable();
          per_.remove(index);
          onChanged();
        } else {
          perBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Person.person.Builder getPerBuilder(
          int index) {
        return getPerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Person.personOrBuilder getPerOrBuilder(
          int index) {
        if (perBuilder_ == null) {
          return per_.get(index);  } else {
          return perBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public java.util.List<? extends Person.personOrBuilder>
           getPerOrBuilderList() {
        if (perBuilder_ != null) {
          return perBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(per_);
        }
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Person.person.Builder addPerBuilder() {
        return getPerFieldBuilder().addBuilder(
            Person.person.getDefaultInstance());
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public Person.person.Builder addPerBuilder(
          int index) {
        return getPerFieldBuilder().addBuilder(
            index, Person.person.getDefaultInstance());
      }
      /**
       * <code>repeated .example.person Per = 1;</code>
       */
      public java.util.List<Person.person.Builder>
           getPerBuilderList() {
        return getPerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Person.person, Person.person.Builder, Person.personOrBuilder>
          getPerFieldBuilder() {
        if (perBuilder_ == null) {
          perBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Person.person, Person.person.Builder, Person.personOrBuilder>(
                  per_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          per_ = null;
        }
        return perBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.all_person)
    }

    // @@protoc_insertion_point(class_scope:example.all_person)
    private static final Person.all_person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person.all_person();
    }

    public static Person.all_person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<all_person>
        PARSER = new com.google.protobuf.AbstractParser<all_person>() {
      @Override
      public all_person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new all_person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<all_person> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<all_person> getParserForType() {
      return PARSER;
    }

    @Override
    public Person.all_person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_student_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_person_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_all_person_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_all_person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014person.proto\022\007example\"\221\001\n\007student\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006weight\030\003 \001(\001\022\013\n" +
      "\003seq\030\004 \001(\003\022\017\n\007address\030\005 \001(\t\022\"\n\006direct\030\006 " +
      "\001(\0162\022.example.Direction\022\014\n\004flag\030\007 \001(\010\022\014\n" +
      "\004imgs\030\010 \001(\014\"V\n\006person\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022!\n\007student\030\003 \001(\0132\020.example.stude" +
      "nt\022\017\n\007address\030\004 \001(\014\"*\n\nall_person\022\034\n\003Per" +
      "\030\001 \003(\0132\017.example.person*2\n\tDirection\022\010\n\004" +
      "LEFT\020\000\022\t\n\005RIGHT\020\001\022\006\n\002UP\020\002\022\010\n\004DOWN\020\003b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_student_descriptor,
        new String[] { "Id", "Name", "Weight", "Seq", "Address", "Direct", "Flag", "Imgs", });
    internal_static_example_person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_person_descriptor,
        new String[] { "Id", "Name", "Student", "Address", });
    internal_static_example_all_person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_example_all_person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_all_person_descriptor,
        new String[] { "Per", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
