// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.platform.dto;

public final class Stu {
  private Stu() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code example.Direction}
   */
  public enum Direction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LEFT = 0;</code>
     */
    LEFT(0),
    /**
     * <code>RIGHT = 1;</code>
     */
    RIGHT(1),
    /**
     * <code>UP = 2;</code>
     */
    UP(2),
    /**
     * <code>DOWN = 3;</code>
     */
    DOWN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LEFT = 0;</code>
     */
    public static final int LEFT_VALUE = 0;
    /**
     * <code>RIGHT = 1;</code>
     */
    public static final int RIGHT_VALUE = 1;
    /**
     * <code>UP = 2;</code>
     */
    public static final int UP_VALUE = 2;
    /**
     * <code>DOWN = 3;</code>
     */
    public static final int DOWN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Direction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Direction forNumber(int value) {
      switch (value) {
        case 0: return LEFT;
        case 1: return RIGHT;
        case 2: return UP;
        case 3: return DOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Direction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Direction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
            public Direction findValueByNumber(int number) {
              return Direction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.platform.dto.Stu.getDescriptor().getEnumTypes().get(0);
    }

    private static final Direction[] VALUES = values();

    public static Direction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Direction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:example.Direction)
  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double weight = 3;</code>
     * @return The weight.
     */
    double getWeight();

    /**
     * <code>int64 seq = 4;</code>
     * @return The seq.
     */
    long getSeq();

    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The enum numeric value on the wire for direct.
     */
    int getDirectValue();
    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The direct.
     */
    com.platform.dto.Stu.Direction getDirect();

    /**
     * <code>bool flag = 7;</code>
     * @return The flag.
     */
    boolean getFlag();

    /**
     * <code>.google.protobuf.Timestamp birthday = 8;</code>
     * @return Whether the birthday field is set.
     */
    boolean hasBirthday();
    /**
     * <code>.google.protobuf.Timestamp birthday = 8;</code>
     * @return The birthday.
     */
    com.google.protobuf.Timestamp getBirthday();
    /**
     * <code>.google.protobuf.Timestamp birthday = 8;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder();
  }
  /**
   * Protobuf type {@code example.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
      direct_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 25: {

              weight_ = input.readDouble();
              break;
            }
            case 32: {

              seq_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              direct_ = rawValue;
              break;
            }
            case 56: {

              flag_ = input.readBool();
              break;
            }
            case 66: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (birthday_ != null) {
                subBuilder = birthday_.toBuilder();
              }
              birthday_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthday_);
                birthday_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platform.dto.Stu.internal_static_example_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platform.dto.Stu.internal_static_example_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platform.dto.Stu.Student.class, com.platform.dto.Stu.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private double weight_;
    /**
     * <code>double weight = 3;</code>
     * @return The weight.
     */
    @java.lang.Override
    public double getWeight() {
      return weight_;
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private long seq_;
    /**
     * <code>int64 seq = 4;</code>
     * @return The seq.
     */
    @java.lang.Override
    public long getSeq() {
      return seq_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECT_FIELD_NUMBER = 6;
    private int direct_;
    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The enum numeric value on the wire for direct.
     */
    @java.lang.Override public int getDirectValue() {
      return direct_;
    }
    /**
     * <code>.example.Direction direct = 6;</code>
     * @return The direct.
     */
    @java.lang.Override public com.platform.dto.Stu.Direction getDirect() {
      @SuppressWarnings("deprecation")
      com.platform.dto.Stu.Direction result = com.platform.dto.Stu.Direction.valueOf(direct_);
      return result == null ? com.platform.dto.Stu.Direction.UNRECOGNIZED : result;
    }

    public static final int FLAG_FIELD_NUMBER = 7;
    private boolean flag_;
    /**
     * <code>bool flag = 7;</code>
     * @return The flag.
     */
    @java.lang.Override
    public boolean getFlag() {
      return flag_;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp birthday_;
    /**
     * <code>.google.protobuf.Timestamp birthday = 8;</code>
     * @return Whether the birthday field is set.
     */
    @java.lang.Override
    public boolean hasBirthday() {
      return birthday_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp birthday = 8;</code>
     * @return The birthday.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getBirthday() {
      return birthday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthday_;
    }
    /**
     * <code>.google.protobuf.Timestamp birthday = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder() {
      return getBirthday();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (weight_ != 0D) {
        output.writeDouble(3, weight_);
      }
      if (seq_ != 0L) {
        output.writeInt64(4, seq_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (direct_ != com.platform.dto.Stu.Direction.LEFT.getNumber()) {
        output.writeEnum(6, direct_);
      }
      if (flag_ != false) {
        output.writeBool(7, flag_);
      }
      if (birthday_ != null) {
        output.writeMessage(8, getBirthday());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, weight_);
      }
      if (seq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, seq_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (direct_ != com.platform.dto.Stu.Direction.LEFT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, direct_);
      }
      if (flag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, flag_);
      }
      if (birthday_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getBirthday());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.platform.dto.Stu.Student)) {
        return super.equals(obj);
      }
      com.platform.dto.Stu.Student other = (com.platform.dto.Stu.Student) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Double.doubleToLongBits(getWeight())
          != java.lang.Double.doubleToLongBits(
              other.getWeight())) return false;
      if (getSeq()
          != other.getSeq()) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (direct_ != other.direct_) return false;
      if (getFlag()
          != other.getFlag()) return false;
      if (hasBirthday() != other.hasBirthday()) return false;
      if (hasBirthday()) {
        if (!getBirthday()
            .equals(other.getBirthday())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeq());
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + DIRECT_FIELD_NUMBER;
      hash = (53 * hash) + direct_;
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFlag());
      if (hasBirthday()) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthday().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.platform.dto.Stu.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platform.dto.Stu.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platform.dto.Stu.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.platform.dto.Stu.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.platform.dto.Stu.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.platform.dto.Stu.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.platform.dto.Stu.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Student)
        com.platform.dto.Stu.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.platform.dto.Stu.internal_static_example_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.platform.dto.Stu.internal_static_example_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.platform.dto.Stu.Student.class, com.platform.dto.Stu.Student.Builder.class);
      }

      // Construct using com.platform.dto.Stu.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        weight_ = 0D;

        seq_ = 0L;

        address_ = "";

        direct_ = 0;

        flag_ = false;

        if (birthdayBuilder_ == null) {
          birthday_ = null;
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.platform.dto.Stu.internal_static_example_Student_descriptor;
      }

      @java.lang.Override
      public com.platform.dto.Stu.Student getDefaultInstanceForType() {
        return com.platform.dto.Stu.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.platform.dto.Stu.Student build() {
        com.platform.dto.Stu.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.platform.dto.Stu.Student buildPartial() {
        com.platform.dto.Stu.Student result = new com.platform.dto.Stu.Student(this);
        result.id_ = id_;
        result.name_ = name_;
        result.weight_ = weight_;
        result.seq_ = seq_;
        result.address_ = address_;
        result.direct_ = direct_;
        result.flag_ = flag_;
        if (birthdayBuilder_ == null) {
          result.birthday_ = birthday_;
        } else {
          result.birthday_ = birthdayBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.platform.dto.Stu.Student) {
          return mergeFrom((com.platform.dto.Stu.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.platform.dto.Stu.Student other) {
        if (other == com.platform.dto.Stu.Student.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        if (other.getSeq() != 0L) {
          setSeq(other.getSeq());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.direct_ != 0) {
          setDirectValue(other.getDirectValue());
        }
        if (other.getFlag() != false) {
          setFlag(other.getFlag());
        }
        if (other.hasBirthday()) {
          mergeBirthday(other.getBirthday());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.platform.dto.Stu.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.platform.dto.Stu.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>double weight = 3;</code>
       * @return The weight.
       */
      @java.lang.Override
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>double weight = 3;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(double value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        
        weight_ = 0D;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <code>int64 seq = 4;</code>
       * @return The seq.
       */
      @java.lang.Override
      public long getSeq() {
        return seq_;
      }
      /**
       * <code>int64 seq = 4;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(long value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 seq = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        
        seq_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 5;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private int direct_ = 0;
      /**
       * <code>.example.Direction direct = 6;</code>
       * @return The enum numeric value on the wire for direct.
       */
      @java.lang.Override public int getDirectValue() {
        return direct_;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @param value The enum numeric value on the wire for direct to set.
       * @return This builder for chaining.
       */
      public Builder setDirectValue(int value) {
        
        direct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @return The direct.
       */
      @java.lang.Override
      public com.platform.dto.Stu.Direction getDirect() {
        @SuppressWarnings("deprecation")
        com.platform.dto.Stu.Direction result = com.platform.dto.Stu.Direction.valueOf(direct_);
        return result == null ? com.platform.dto.Stu.Direction.UNRECOGNIZED : result;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @param value The direct to set.
       * @return This builder for chaining.
       */
      public Builder setDirect(com.platform.dto.Stu.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        direct_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.example.Direction direct = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirect() {
        
        direct_ = 0;
        onChanged();
        return this;
      }

      private boolean flag_ ;
      /**
       * <code>bool flag = 7;</code>
       * @return The flag.
       */
      @java.lang.Override
      public boolean getFlag() {
        return flag_;
      }
      /**
       * <code>bool flag = 7;</code>
       * @param value The flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlag(boolean value) {
        
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool flag = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlag() {
        
        flag_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp birthday_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthdayBuilder_;
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       * @return Whether the birthday field is set.
       */
      public boolean hasBirthday() {
        return birthdayBuilder_ != null || birthday_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       * @return The birthday.
       */
      public com.google.protobuf.Timestamp getBirthday() {
        if (birthdayBuilder_ == null) {
          return birthday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthday_;
        } else {
          return birthdayBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      public Builder setBirthday(com.google.protobuf.Timestamp value) {
        if (birthdayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthday_ = value;
          onChanged();
        } else {
          birthdayBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      public Builder setBirthday(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (birthdayBuilder_ == null) {
          birthday_ = builderForValue.build();
          onChanged();
        } else {
          birthdayBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      public Builder mergeBirthday(com.google.protobuf.Timestamp value) {
        if (birthdayBuilder_ == null) {
          if (birthday_ != null) {
            birthday_ =
              com.google.protobuf.Timestamp.newBuilder(birthday_).mergeFrom(value).buildPartial();
          } else {
            birthday_ = value;
          }
          onChanged();
        } else {
          birthdayBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      public Builder clearBirthday() {
        if (birthdayBuilder_ == null) {
          birthday_ = null;
          onChanged();
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBirthdayBuilder() {
        
        onChanged();
        return getBirthdayFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder() {
        if (birthdayBuilder_ != null) {
          return birthdayBuilder_.getMessageOrBuilder();
        } else {
          return birthday_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : birthday_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBirthdayFieldBuilder() {
        if (birthdayBuilder_ == null) {
          birthdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBirthday(),
                  getParentForChildren(),
                  isClean());
          birthday_ = null;
        }
        return birthdayBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.Student)
    }

    // @@protoc_insertion_point(class_scope:example.Student)
    private static final com.platform.dto.Stu.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.platform.dto.Stu.Student();
    }

    public static com.platform.dto.Stu.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.platform.dto.Stu.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\007example\032\037google/protobu" +
      "f/timestamp.proto\"\261\001\n\007Student\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\022\016\n\006weight\030\003 \001(\001\022\013\n\003seq\030\004" +
      " \001(\003\022\017\n\007address\030\005 \001(\t\022\"\n\006direct\030\006 \001(\0162\022." +
      "example.Direction\022\014\n\004flag\030\007 \001(\010\022,\n\010birth" +
      "day\030\010 \001(\0132\032.google.protobuf.Timestamp*2\n" +
      "\tDirection\022\010\n\004LEFT\020\000\022\t\n\005RIGHT\020\001\022\006\n\002UP\020\002\022" +
      "\010\n\004DOWN\020\003B\027\n\020com.platform.dtoB\003Stub\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_example_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Weight", "Seq", "Address", "Direct", "Flag", "Birthday", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
